LabelingSystem-master/labelingsystem/task/urls.py
from django.conf.urls import url

from .views import *

app_name = 'task'

urlpatterns = [
  url(r'^task_list/$', TaskListView.as_view(), name='task_list'),
  url(r'^take_task/(?P<pk>[-\w]+)$', TakeTaskView.as_view(), name='take_task'),
  url(r'^task_complete/$', TaskCompleteView.as_view(), name='task_complete'),
  url(r'^task_empty/$', TaskEmptyView.as_view(), name='task_empty'),
  url(r'^create_task/$', CreateTaskView.as_view(), name='create_task'),
  url(r'^create_task_success/$', CreateTaskSuccessView.as_view(), name='create_task_success'),
  url(r'^edit_task/$', EditTaskView.as_view(), name='edit_task'),
  url(r'^edit_task_success/$', EditTaskSuccessView.as_view(), name='edit_task_success'),
  url(r'^update_labeler/$', UpdateLabelerView.as_view(), name='update_labeler'),
  url(r'^update_labeler_success/$', UpdateLabelerSuccessView.as_view(), name='update_labeler_success'),
  url(r'^task_evaluation_list/$', TaskEvaluationListView.as_view(), name='task_evaluation_list'),
  url(r'^task_evaluation_empty/$', TaskEvaluationEmptyView.as_view(), name='task_evaluation_empty'),
  url(r'^task_evaluation_detail/(?P<pk>[-\w]+)$', TaskEvaluationDetailView.as_view(), name='task_evaluation_detail'),
  url(r'^task_participation_list/$', TaskParticipationListView.as_view(), name='task_participation_list'),
  url(r'^task_participation_empty/$', TaskParticipationEmptyView.as_view(), name='task_participation_empty'),
]

labelingsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth.views import login
from .views import *

admin.site.site_header = 'CrowdTagger'
admin.site.site_title = 'CrowdTagger System'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('account:login'))),
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^admin_index/$', AdminIndexView.as_view(), name='admin_index'),
    url(r'^super_admin_index/$', SuperAdminIndexView.as_view(), name='super_admin_index'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^task/', include('task.urls', namespace='task')),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^response/', include('response.urls', namespace='response')),
    url(r'^classify/', include('classify.urls', namespace='classify')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^select2/', include('django_select2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url

from .views import *

app_name = 'post'

urlpatterns = [
  url(r'^create_post_response/(?P<task_pk>[-\w]+)&(?P<post_pk>[-\w]+)$', create_post_response, name='create_post_response'),
]

task/urls.py
from django.conf.urls import url

from .views import *
app_name = 'task'

urlpatterns = [
  url(r'^task_list/$', TaskListView.as_view(), name='task_list'),
  url(r'^create_task/get_table/$', get_table, name = "get_table_all"),
  url(r'^create_task/get_table_all/$', get_table_all, name = "get_table"),
  url(r'^take_task/(?P<pk>[-\w]+)$', TakeTaskView.as_view(), name='take_task'),
  url(r'^task_complete/$', TaskCompleteView.as_view(), name='task_complete'),
  url(r'^task_empty/$', TaskEmptyView.as_view(), name='task_empty'),
  url(r'^create_task/$', CreateTaskView.as_view(), name='create_task'),
  url(r'^create_task_success/$', CreateTaskSuccessView.as_view(), name='create_task_success'),
  url(r'^load_database/$', LoadDatabaseView.as_view(), name='load_database'),
  url(r'^load_database_success/$', LoadDatabaseSuccessView.as_view(), name='load_database_success'),
  url(r'^load_database_fail/$', LoadDatabaseFailView.as_view(), name='load_database_fail'),
  url(r'^edit_task/$', EditTaskView.as_view(), name='edit_task'),
  url(r'^edit_task_success/$', EditTaskSuccessView.as_view(), name='edit_task_success'),
  url(r'^update_labeler/$', UpdateLabelerView.as_view(), name='update_labeler'),
  url(r'^update_labeler_success/$', UpdateLabelerSuccessView.as_view(), name='update_labeler_success'),
  url(r'^task_evaluation_list/$', TaskEvaluationListView.as_view(), name='task_evaluation_list'),
  url(r'^task_evaluation_empty/$', TaskEvaluationEmptyView.as_view(), name='task_evaluation_empty'),
  url(r'^task_evaluation_detail/(?P<pk>[-\w]+)$', TaskEvaluationDetailView.as_view(), name='task_evaluation_detail'),
  url(r'^task_participation_list/$', TaskParticipationListView.as_view(), name='task_participation_list'),
  url(r'^task_participation_empty/$', TaskParticipationEmptyView.as_view(), name='task_participation_empty'),
  url(r'^connection_list/$', ConnectionListView.as_view(), name='connection_list'),
  url(r'^connection_list/delete_connection/$', delete_connection, name='delete_connection'),
  url(r'^connection_list/(?P<pk>\d+)/$', ConnectionDetailView.as_view(), name='connection_detail'),
  url(r'^connection_list_modal/$', ConnectionListModalView.as_view(), name='connection_list_modal'),
  url(r'^connection_list_modal/delete_connection_modal/$', delete_connection_modal, name='delete_connection_modal'),
  url(r'^connection_list_modal/(?P<pk>\d+)/$', ConnectionDetailModalView.as_view(), name='connection_detail_modal'),
  url(r'^load_database_modal/$', LoadDatabaseModalView.as_view(), name='load_database_modal'),
  url(r'^merge_database/$', merge_database, name='merge_database'),
]

label/models.py
from django.db import models


class Label(models.Model):

  class Meta:
    verbose_name = 'label'
    verbose_name_plural = 'labels'

  content = models.CharField(
                            max_length=1000,
                            blank=False,
                            default=None,
                            verbose_name='content'
                            )

  def __str__(self):
    return self.content

class Label1(models.Model):

  class Meta:
    verbose_name = 'label'
    verbose_name_plural = 'labels'
    
  content = models.CharField(
                            max_length=1000,
                            blank=False,
                            default=None,
                            verbose_name='content'
                            )
  def __str__(self):
    return self.content

LabelingSystem-master/labelingsystem/task/views.py
from django.shortcuts import render
from django.shortcuts import get_list_or_404, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, TemplateView, FormView, DetailView
from .models import Task, Participation,Document
from label.models import Label
from post.models import Post
from response.models import PostResponse
from collections import deque
from collections import Counter
from .forms import CreateTaskForm
from .forms import EditTaskForm
from flask import Flask, request
from .forms import UpdateLabelerForm

from nltk.metrics.agreement import AnnotationTask

from itertools import combinations

import csv
import datetime
import os
from django.conf import settings
from django.views.decorators.http import require_POST

import random
from django.db.models import Q

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.


class TaskListView(LoginRequiredMixin, ListView):
	model = Task
	template_name = 'task/task_list.html'

	def dispatch(self, request, *args, **kwargs):
		user = self.request.user
		#post_list = []
		self.array = []
		self.task_complete = False
		try:
			task_ids = Participation.objects.filter(labeler=user.email).values('task').distinct()			
			get_list_or_404(task_ids)			
			self.task_list = Task.objects.filter(id__in=task_ids)
			get_list_or_404(self.task_list)
			
		except:			
			  return redirect('/task/task_empty', permanent=True)
		 
		for taskid in self.task_list:
			try :
				#print(taskid)
				task_object = get_object_or_404(Task, pk=taskid.pk)
				#print(task_object)
				post_response_ids = PostResponse.objects.filter(task=taskid.pk, responder=self.request.user.pk).values_list('post__id', flat=True).distinct()
				post_list = get_list_or_404(taskid.post_list.filter(~Q(id__in=post_response_ids)))		
				#print("here")	
				if len(post_response_ids) >= int(Task.objects.filter(id=taskid.pk).values_list('num_labelers', flat=True).first()):
					print ("herrrrr", len(post_response_ids),int(Task.objects.filter(id=taskid.pk).values_list('num_labelers', flat=True).first()) )
					self.array.append(True)
				else :
					self.array.append(False)			
	#			self.array.append(False)
			except:
				#print(post_list)
				self.array.append(True)
	
		return super(TaskListView, self).dispatch(request, *args, **kwargs)

	def get_queryset(self):
		return self.task_list

	def get_context_data(self, **kwargs):
		context = super(TaskListView, self).get_context_data(**kwargs)
		context['task_list'] = self.get_queryset()
		context['task_complete_list'] = self.array
		return context

class TakeTaskView(LoginRequiredMixin, TemplateView):
	model = Task
	template_name = 'task/take_task.html'
	ctr = 1
	def dispatch(self, request, *args, **kwargs):
		self.task = get_object_or_404(Task, pk=self.kwargs['pk'])
		#print(self.task)
		post_list = []
		temppost = ''
		post_response_ids = PostResponse.objects.filter(task=self.task.pk, responder=self.request.user.pk).values_list('post__id', flat=True).distinct()
#		self.num_labeled = len(PostResponse.objects.filter(task=self.task.pk).values_list('responder__email', flat=True))
		self.num_labeled = len(PostResponse.objects.filter(task=self.task.pk, responder=self.request.user.pk).values_list('responder__email', flat=True))
		self.num_posts = list(Task.objects.filter(id=self.task.pk).values_list('num_posts').first())[0]
		if int(self.num_labeled) /int(self.num_posts) * 100 > 100 :
			self.scaled = 100;
		else :
			self.scaled = int(self.num_labeled) /int(self.num_posts) * 100;
		#print(post_response_ids)
		least_responded_post = Task.objects.filter(id=self.task.pk).values_list('num_labelers', flat=True).first()
		print (least_responded_post)
		#Task.objects.filter(id__in=task_ids)
		lst_reponded_list = []
		res_reponded_list = []
		try:
			temp = get_list_or_404(self.task.post_list.filter(~Q(id__in=post_response_ids)))			
			#temppost = post_list;
#			print(post_list[0])
			l1 = list(self.task.post_list.all().filter(task=self.task.pk).values_list('id', flat=True))
			l2 = list(post_response_ids)
			diff_list = [item for item in l1 if not item in l2]
			print(diff_list)
			for responded_post in diff_list:
				responder_ids = list(PostResponse.objects.filter(task=self.task.pk, post=responded_post).values_list('responder__id', flat=True).distinct())
				#print (len(responder_ids))
				#print('hereeee')
				#print (responded_post)
				#print (least_responded_post)
				lnt = len(responder_ids)
				lsts = int(least_responded_post)
				print("number of reponders for this post", lnt)
				if lnt<lsts:
					#least_responded_post = len(responder_ids)
					#print("hereee")
					post_list = Post.objects.filter(id=responded_post)
					#print('hereee')
					print("list of posts not responded by this user", post_list)					
					lst_reponded_list.append(len(responder_ids)+1)
					#lst_reponded_list = sorted(lst_reponded_list)
					least_responded_post = min(lst_reponded_list)#[0]
					#print(least_responded_post )
					break				
				else:
					lst_reponded_list.append(len(responder_ids))	
					res_reponded_list.append(Post.objects.filter(id=responded_post))
					print(responded_post)		
			if post_list == [] :
				#= min(lst_reponded_list)
				post_list = res_reponded_list[lst_reponded_list.index(min(lst_reponded_list))]
				#print('all were labeled more than min')
				#print(res_reponded_list)
			if responded_post == None :
				post_list = temp
				#print ('here here')			
			#print ("before return")
			
			#least_responded_post = sorted(least_responded_post)
			#print(least_responded_post[0])	

			#if self.task.random_label=='T':
			#	random.shuffle(post_list)
			
			#ctr = ctr + 1			
			
			#self.task.filter(post_list).update(task=self.task.pk)
			self.post = post_list[0]
			print (self.post)
		except:
			#self.complete = True
			#print(get_list_or_404(self.task.post_list.filter(~Q(id__in=post_response_ids))))
			#if post_list==[]:
			#self.complete = True	
			return redirect('/task/task_complete', permanent=True)

		return super(TakeTaskView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(TakeTaskView, self).get_context_data(**kwargs)
		context['task'] = self.task
		context['post'] = self.post
		#print(self.post)
		#context['complete'] = self.complete
		context['label_list'] = self.task.label_list.all()
		context['post_list'] = self.task.post_list.all()
		context['num_labeled'] = self.num_labeled;
		print (int(self.num_labeled) /int(self.num_posts) * 100)		
		context['scaled'] = self.scaled;

		return context

class TaskCompleteView(LoginRequiredMixin, TemplateView):
    template_name = 'task/task_complete.html'

class TaskEmptyView(LoginRequiredMixin, TemplateView):
    template_name = 'task/task_empty.html'

class CreateTaskView(LoginRequiredMixin, FormView):
	model = Task
	form_class = CreateTaskForm
	
	template_name = 'task/create_task.html'
	success_url = '/task/create_task_success'
	
#	def upload_file(request):
#		if request.method == 'POST':
#			form = CreateTaskForm(request.POST, request.FILES)
#			print ('here')
#	        if form.is_valid():
        	  #  handle_uploaded_file(request.FILES['file'])
	           # return HttpResponseRedirect('/success/url/')
#		print (request.FILES['task_upload_file'])
#	    else:
#	        form = UploadFileForm()
#	    return render(request, 'upload.html', {'form': form})
#	from django.views.decorators.http import require_POST

#	@require_POST
#	def file_upload(self,request):
 #           save_path = os.path.join(settings.MEDIA_ROOT, 'postlist',request.files['task_upload_file'])
 #           path = default_storage.save(save_path, request.files['task_upload_file'])
 #           return default_storage.path(path)
	
	
	def form_valid(self, form):
		
#			if form.is_valid():
				task_title = form.cleaned_data['Task Title']
				task_description = form.cleaned_data['Task Description']
				task_upload_file = form.cleaned_data['Upload Task Posts and Labels']
				#task_upload_file  = CreateTaskForm(
				#self.fields['Upload Task Posts and Labels']
				#doc=Document(document=self.get_form_kwargs().get('files')['Upload Task Posts and Labels'])
				#doc.save()
				#print (self.get_form_kwargs().get('files')['Upload Task Posts and Labels'])
				#task_id = doc.id
				#print(doc)
				#task_upload_file = self.get_form_kwargs().get('files')['Upload Task Posts and Labels']
				#)	
				#task_upload_file.save()
				#rint (task_upload_file)
				task_num_labelers = form.cleaned_data['Min Number of Labelers']
		#print(task_upload_file.document)
				task_num_posts = form.cleaned_data['Min Number of Posts']
				task_random_label = form.cleaned_data['Label Posts in Random Order']
				quiz_title = form.cleaned_data['Quiz Title']
				quiz_description = form.cleaned_data['Quiz Description']
				max_posts = form.cleaned_data['Number of Questions']
				pass_mark = form.cleaned_data['Pass Mark']
				quiz_upload_file = form.cleaned_data['Upload Quiz Posts and Labels']
				participating_coders = form.cleaned_data['Participating Labelers']
				#print (request.FILES['task_upload_file'])
				#self.file_upload(request)
#		temp = request.FILES['task_upload_file']
#		print (temp)
		
				prerequisite = form.cleaned_data['Choose Quiz']#form.create_quiz(quiz_title, quiz_description, max_posts, pass_mark, quiz_upload_file, self.request.user)
				task = form.create_task(task_title, task_description, self.request.user, prerequisite, task_num_labelers, task_num_posts, task_random_label, task_upload_file)
		#print (task)
				form.send_email(task)
				#task.full_clean()
		#post_list = get_list_or_404(self.task.post_list.filter(~Q(id__in=post_response_ids)))			
		#if self.task.random_label=='T':
		#	random.shuffle(post_list)
				return super(CreateTaskView, self).form_valid(form)
#		print (request.FILES['task_upload_file'])
#		else:
#			form = CreateTaskForm()
#	def file_upload(request):

task/templates/task/create_task.html
{% extends "base_site.html" %}
<style>
.modal {
   z-index: 1050;
}
.modal-backdrop {
   z-index: 1040;
}
.modal-body{
    max-height: 500px;
    overflow-y: scroll;
}
</style>
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>

&rsaquo; Create Task
</div>
{% endblock breadcrumbs %}
{% block content %}
<div class="container-fluid">
	{% csrf_token %}
	{% crispy form  %}

</div>	
{% endblock content %}

task/templates/task/create_task_success.html
{% extends "base_site.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>

&rsaquo; Create Task Success
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">

	<div class="row">
		<div class="col-md-12">
			<h1>Hi, {{ request.user }}!</h1>
			<br>
			<p>
				You have successfully created new task!
			</p>
			<p>You can evaluate your task in the task evaluation list.</p>
			<br>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" style="text-align: center;">
			<a href="{% url 'task:task_evaluation_list' %}">
				<div class="btn btn-info btn-lg start_quiz">Task Evaluation List</div>
			</a>
		</div>
	</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li style="color:red; font-size:120%;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>
{% endblock content %}

task/templates/task/custom_button.html
{% include "django/forms/widgets/input.html" %}
<button name = 'removefield' style="font-size:14px;color:red"" onclick="remove_field('{{widget.name}}')" ><i class="fa fa-close"></i></button>

task/templates/task/edit_task_success.html
{% extends "base_site.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>
&rsaquo;
<a href="{% url 'admin_index' %}">Admin Home </a>
&rsaquo; Create Task Success
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">

	<div class="row">
		<div class="col-md-12">
			<h1>Hi, {{ request.user }}!</h1>
			<br>
			<p>
				You have successfully created new task!
			</p>
			<p>You can evaluate your task in the task evaluation list.</p>
			<br>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" style="text-align: center;">
			<a href="{% url 'task:task_evaluation_list' %}">
				<div class="btn btn-info btn-lg start_quiz">Task Evaluation List</div>
			</a>
		</div>
	</div>

</div>
{% endblock content %}

task/templates/task/take_task.html
{% extends "base_site.html" %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'task/css/take_task.css' %}">
{% endblock extrastyle %}

{% block extrascript %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
<script src="http://malsup.github.com/jquery.form.js"></script> 
<script type="text/javascript" src="{% static 'task/js/take_task.js' %}"></script>
{% endblock extrascript %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}"> Home </a>
&rsaquo;
<a href="{% url 'task:task_list' %}"> Task List </a>
&rsaquo; Take Task
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">
	<div id="prolog">
		<div class="row">
			<div class="col-md-12">
				<h1></h1>
				<!--p style="text-align: center;">
					 You have labeled "{{ num_labeled }}" posts out of "{{ task.num_posts }}" posts so far!			
				</p>
				<p style="text-align: center;">Continue labeling or press <a href="{% url 'task:task_list' %}">Exit</a> to return to the tasks list!</p> 
				<p style="text-align: center;">-------------------------------------------------------</p-->
				
				<br>
				<br>
			</div>
			
		</div>
		<div class="row">
			<div class="col-md-12" style="text-align: center;">
				<!--div class="btn btn-info btn-lg start_task">Continue</div-->
			</div>
		</div>
	</div>
	
	<form id="post_form" action="{% url 'response:create_post_response' task.pk post.pk %}" method="POST">
		{% csrf_token %} 
		
			<!--button onclick="move()">Click Me</button--> 
			<style>
			#myProgress {
  height: 3em;
  width: 100%;
  background-color: #ddd;
  color: black;
  position: relative;
}
#myProgress:before {
  content: attr(data-label);
  font-size: 1.5em;
  position: absolute;
  text-align: center;
  top: 5px;
  left: 0;
  right: 0;
}
			
			</style>
			<h1>Task Title :  {{task}}</h1>
			<h2>Labeling Progress</h2>
	 		<div id="myProgress" data-label="{{scaled}}% Complete">			   				
			  <div id="myBar" style="width:{{scaled}}%; height:3em; background-color: #4CAF50;"></div>
			</div>
			
				<br>
				<br>
		<div class="row" >
			

			<div class="col-sm-12">
				<div class="loader">
					<div class="card">

						<div class="post">
							<h3>
								<span id="post_{{ post.id }}"> {{ post }}</span>
							</h3>
						</div>
						<ul>

							{% for label in label_list %}
							<li class="btn btn-default">
								<input id="label_{{ label.id }}" type="radio" name="post_{{ post.id }}" value="{{ label.id }}">
								<label for="label_{{ label.id }}" class="element-animation">{{ label }}</label>
								 
								<div class="check"></div>
							</li>
							
							{% endfor %}
								

						</ul>
					</div>
				</div>
				<div class="text-muted">
					<span class="label"></span>
				</div>
				
			</div>
			

		</div>
		<div class="col-md-12" style="text-align: left;">
					<a href="{% url 'task:task_list' %}" class="btn btn-info btn-lg">Exit Task</a>
		</div>	
	</form>

</div>
{% endblock content %}

task/templates/task/task_evaluation_detail.html
{% extends "base_site.html" %}
{% load static %}
{% load check_prerequisite %}

{% block extrastyle %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock extrastyle %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>

&rsaquo;	
<a href="{% url 'task:task_evaluation_list' %}">Task Evaluation List </a>
&rsaquo; Task Evaluation Detail
</div>
{% endblock breadcrumbs %}



{% block content %}
<!--div class="container-fluid"-->
	<!--div class="col-sm-12"-->
		<h1>Kappa Evaluation for {{task}} </h1><h2><a href={{tablefile}} download>[download table as a file]</a></h2>
		<table class="table table-striped">
			<!--thead>
				<tr class="table-head">
					<th>Labeler Pairs</th>
					<th>Kappa</th>
				</tr>
			</thead-->
			<tbody>
			{% for row in head %}
			<thead>
			
			<tr><th></th>
				{% for col in row %}
					{% if col != "(List continues...)" %}
	                                      <th>{{ col }}</th>
        	                        {% else %}
                	                       <th><a href="" >(...)</a></th>
                        	         {% endif %}

									
														
								
				
				{% endfor %}
			</tr>
			<thead>
			{% endfor %}
			{% for row in head %} 
			<tr>
				{% for col in row %}
				<tr>
					 {% if col != "(List continues...)" %}
                                              <th>{{ col }}</th>
					 {% else %}
						<th><a href={{tablefile}} download>[See full list]</a></th>
					 {% endif %}
					
					{% for rowp in kappa.0 %}                               		 		                               													
								<!--td></td-->
						
							{% if col in rowp %} 							
								<td>{{ rowp.2 }}</td>
							{% endif %}  
					
					{% endfor %}			
				</tr>
				{% endfor %}				
			</tr>
			{% endfor %}
			
			</tbody>
		</table>
		<br/>
		<h1>Krippendorff's alpha: &nbsp {{ alpha }}</h1>
		<br/>
		<!--h1>"{{ task }}" Evaluation</h1-->
		<h1>Evaluation Details for {{task}}</h1><h2><a href={{tablefile1}}>[download table as a file]</a></h2>
		<table class="table table-striped">
			<thead>
				<tr class="table-head">
					<th>Post</th>
					{% for coder_email in coder_email_list %}
						{% if coder_email != "(List continues...)" %}
							<th>{{ coder_email }}</th>
						{% else %}
							<th><a href={{tablefile1}} download >[See Full List]</a></th>
						{% endif %}
						
					{% endfor %}
					<th>Majority Vote</th>
				</tr>
			</thead>
			<tbody>
				{% for row in array %}
				<tr>
				{% if forloop.counter > 5 %}
					<tr><td>...</td></tr>	 									
				{% else %}
									
					{% for col in row %}
						<td>{{ col }}</td>
					{% endfor %}
				</tr>
				{% endif %}
				
				{% endfor %}

				
			</tbody>
			
		</table>
		<div>
    <input type="button" id="button_1" name="merge" value="Merge Majority Vote to database">  
		</div>
	</div>

</div>
<script>
$(document).ready(function() {
  $("#button_1").click(function(e) {

    e.preventDefault();
    var col_name = prompt("Please type in the field name(MYSQL) or dataset name(AsterixDB) you want to store the majority vote in:", "");
    if(confirm('Begin to merge majority into original database. Click OK to continue.'))
    {
    $.ajax({
      type: "POST",
      url: "/task/merge_database/",
      data: {
        id:  "{{task_id}}",
        path: "{{tablefile1}}",
        name: col_name
      },
      success: function(result) {
        alert('Transaction Complete');
      },
      error: function(result) {
        alert('Connection error or duplicate field name');
      }
    });
  }
  });
});
</script>


{% endblock content %}

task/templates/task/update_labeler_success.html
{% extends "base_site.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>

&rsaquo; Add or Remove Labeler
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">

	<div class="row">
		<div class="col-md-12">
			<h1>Dear {{ request.user }}!</h1>
			<br>
			<p>
				You have successfully updated the labelers list!
			</p>
			<p>You can now go back and check the task participation list...</p>
			<br>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" style="text-align: center;">
			<a href="{% url 'task:task_participation_list' %}">
				<div class="btn btn-info btn-lg start_quiz">Task Participation List</div>
			</a>
		</div>
	</div>

</div>
{% endblock content %}