LabelingSystem-master/labelingsystem/labelingsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

from .views import *

admin.site.site_header = 'Social Post Analyzer'
admin.site.site_title = 'Social Post Analyzer Labeling System'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('account:login'))),
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'admin_index/$', AdminIndexView.as_view(), name='admin_index'),
    url(r'super_admin_index/$', SuperAdminIndexView.as_view(), name='super_admin_index'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^task/', include('task.urls', namespace='task')),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^response/', include('response.urls', namespace='response')),
    url(r'^classify/', include('classify.urls', namespace='classify')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labelingsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth.views import login
from .views import *

admin.site.site_header = 'CrowdTagger'
admin.site.site_title = 'CrowdTagger System'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('account:login'))),
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^admin_index/$', AdminIndexView.as_view(), name='admin_index'),
    url(r'^super_admin_index/$', SuperAdminIndexView.as_view(), name='super_admin_index'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^task/', include('task.urls', namespace='task')),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^response/', include('response.urls', namespace='response')),
    url(r'^classify/', include('classify.urls', namespace='classify')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^select2/', include('django_select2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url

from .views import *

app_name = 'post'

urlpatterns = [
  url(r'^create_post_response/(?P<task_pk>[-\w]+)&(?P<post_pk>[-\w]+)$', create_post_response, name='create_post_response'),
]

quiz/urls.py
from django.conf.urls import url

from .views import *

app_name = 'quiz'

urlpatterns = [
  url(r'^take_quiz/(?P<pk>[-\w]+)$', TakeQuizView.as_view(), name='take_quiz'),
  url(r'^quiz_success/(?P<pk>[-\w]+)$', QuizSuccessView.as_view(), name='quiz_success'),
  url(r'^create_quiz/$', CreateQuizView.as_view(), name='create_quiz'),
  url(r'^create_quiz_success/$', CreateQuizSuccessView.as_view(), name='create_quiz_success'),
  url(r'^quiz_fail/(?P<pk>[-\w]+)$', QuizFailView.as_view(), name='quiz_fail'),
]

response/urls.py
from django.conf.urls import url

from .views import *

app_name = 'response'

urlpatterns = [
  url(r'^create_post_response/(?P<task_pk>[-\w]+)&(?P<post_pk>[-\w]+)$', create_post_response, name='create_post_response'),
  url(r'^create_quiz_response(?P<pk>[-\w]+)$', create_quiz_response, name='create_quiz_response'),
]

task/urls.py
from django.conf.urls import url

from .views import *
app_name = 'task'

urlpatterns = [
  url(r'^task_list/$', TaskListView.as_view(), name='task_list'),
  url(r'^create_task/get_table/$', get_table, name = "get_table_all"),
  url(r'^create_task/get_table_all/$', get_table_all, name = "get_table"),
  url(r'^take_task/(?P<pk>[-\w]+)$', TakeTaskView.as_view(), name='take_task'),
  url(r'^task_complete/$', TaskCompleteView.as_view(), name='task_complete'),
  url(r'^task_empty/$', TaskEmptyView.as_view(), name='task_empty'),
  url(r'^create_task/$', CreateTaskView.as_view(), name='create_task'),
  url(r'^create_task_success/$', CreateTaskSuccessView.as_view(), name='create_task_success'),
  url(r'^load_database/$', LoadDatabaseView.as_view(), name='load_database'),
  url(r'^load_database_success/$', LoadDatabaseSuccessView.as_view(), name='load_database_success'),
  url(r'^load_database_fail/$', LoadDatabaseFailView.as_view(), name='load_database_fail'),
  url(r'^edit_task/$', EditTaskView.as_view(), name='edit_task'),
  url(r'^edit_task_success/$', EditTaskSuccessView.as_view(), name='edit_task_success'),
  url(r'^update_labeler/$', UpdateLabelerView.as_view(), name='update_labeler'),
  url(r'^update_labeler_success/$', UpdateLabelerSuccessView.as_view(), name='update_labeler_success'),
  url(r'^task_evaluation_list/$', TaskEvaluationListView.as_view(), name='task_evaluation_list'),
  url(r'^task_evaluation_empty/$', TaskEvaluationEmptyView.as_view(), name='task_evaluation_empty'),
  url(r'^task_evaluation_detail/(?P<pk>[-\w]+)$', TaskEvaluationDetailView.as_view(), name='task_evaluation_detail'),
  url(r'^task_participation_list/$', TaskParticipationListView.as_view(), name='task_participation_list'),
  url(r'^task_participation_empty/$', TaskParticipationEmptyView.as_view(), name='task_participation_empty'),
  url(r'^connection_list/$', ConnectionListView.as_view(), name='connection_list'),
  url(r'^connection_list/delete_connection/$', delete_connection, name='delete_connection'),
  url(r'^connection_list/(?P<pk>\d+)/$', ConnectionDetailView.as_view(), name='connection_detail'),
  url(r'^connection_list_modal/$', ConnectionListModalView.as_view(), name='connection_list_modal'),
  url(r'^connection_list_modal/delete_connection_modal/$', delete_connection_modal, name='delete_connection_modal'),
  url(r'^connection_list_modal/(?P<pk>\d+)/$', ConnectionDetailModalView.as_view(), name='connection_detail_modal'),
  url(r'^load_database_modal/$', LoadDatabaseModalView.as_view(), name='load_database_modal'),
  url(r'^merge_database/$', merge_database, name='merge_database'),
]

LabelingSystem-master/labelingsystem/quiz/models.py
from django import forms
from django.db import models
from django.core.validators import MaxValueValidator
from django.conf import settings
from label.models import Label
from post.models import Post
#from .models import Participation
from django.contrib.admin.widgets import FilteredSelectMultiple
from smart_selects.db_fields import ChainedForeignKey 


# Create your models here.
class Quiz(models.Model):
	
	class Meta:
		verbose_name = 'quiz'
		verbose_name_plural = 'quizzes'

	title = models.CharField(
		max_length = 50,
		verbose_name = 'title',
		blank = False)

	description = models.TextField(
		verbose_name = 'description',
		blank = True)

	max_posts = models.PositiveIntegerField(
		blank = True,
		null = True,
		verbose_name = 'max posts')

	pass_mark = models.PositiveIntegerField(
		blank = True,
		default = 0,
		verbose_name = 'pass mark',
		validators = [MaxValueValidator(100)])

	label_list = models.ManyToManyField(
		Label,
		blank = False,
		verbose_name = 'label list',
		editable = False)

	post_list = models.ManyToManyField(
		Post,
		#default = None,
		blank = True,
		verbose_name = 'post list',
		editable = False)

	#postTag = models.ForeignKey(Post)
	#label = ChainedForeignKey(
        #	Post,
        #	chained_field="postTag",
        #	chained_model_field="postTag",
        #	show_all=False,
        #	auto_choose=True,
        #	sort=True)
	
	creator = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete = models.CASCADE,
		verbose_name = 'creator',
		default = 'none',
		blank = False,
		null = False,
		editable = False,)
	upload_quiz = models.FileField(Label,upload_to='post list', default=None, editable=False)

	#creator = models.ForeignKey(
	#	settings.AUTH_USER_MODEL,
	#	on_delete = models.CASCADE,
	#	verbose_name = 'creator',
	#	default = 'none',
	#	blank = False,
	#	null = False)

	

	def __str__(self):
		return self.title

class AnswerKey(models.Model):

	class Meta:
		verbose_name = 'answer key'
		verbose_name_plural = 'answer keys'

	quiz = models.OneToOneField(
		Quiz,
		blank = False)

	def __str__(self):
		return "{} answer key".format(self.quiz)

class Answer(models.Model):

	class Meta:
		verbose_name = 'answer'
		verbose_name_plural = 'answers'

	answer_key = models.ForeignKey(
		AnswerKey,
		blank = False,
		default = None)

	post = models.ForeignKey(
		Post,
		blank = False,
		default = None)

	label = models.ForeignKey(
		Label,
		blank = False,
		default = None)

	def __str__(self):
		return '{0}, {1}'.format(self.post, self.label)

label/models.py
from django.db import models


class Label(models.Model):

  class Meta:
    verbose_name = 'label'
    verbose_name_plural = 'labels'

  content = models.CharField(
                            max_length=1000,
                            blank=False,
                            default=None,
                            verbose_name='content'
                            )

  def __str__(self):
    return self.content

class Label1(models.Model):

  class Meta:
    verbose_name = 'label'
    verbose_name_plural = 'labels'
    
  content = models.CharField(
                            max_length=1000,
                            blank=False,
                            default=None,
                            verbose_name='content'
                            )
  def __str__(self):
    return self.content

post/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):

  class Meta:
    verbose_name = 'post'
    verbose_name_plural = 'posts'

  db_id = models.IntegerField(null=True, blank=True, verbose_name='db_id')
  content = models.CharField(
    max_length=1000,
    blank=False,
    verbose_name='post')

  author = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE,
    verbose_name='creator',
    blank=False,
    default=None,
    null=False)

  def __str__(self):
    return self.content

class Post1(models.Model):

  class Meta:
    verbose_name = 'post1'
    verbose_name_plural = 'posts1'

  db_id = models.IntegerField(null=True, blank=True, verbose_name='db_id')
  content = models.CharField(
          max_length=1000,
          blank=False,
          verbose_name='post1')

  author = models.ForeignKey(
          settings.AUTH_USER_MODEL,
          on_delete=models.CASCADE,
          verbose_name='creator',
          blank=False,
          default=None,
          null=False)

  def __str__(self):
    return self.content

LabelingSystem-master/labelingsystem/quiz/views.py
from django.shortcuts import render
from django.shortcuts import get_list_or_404, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, TemplateView, FormView, DetailView
from .models import Quiz
from response.models import PostResponse
from post.models import Post
from task.models import Task
from label.models import Label

from nltk.metrics.agreement import AnnotationTask

from .forms import CreateQuizForm

import random
from django.db.models import Q

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.
class TakeQuizView(LoginRequiredMixin, TemplateView):
	model = Quiz
	template_name = 'quiz/take_quiz.html'

	def dispatch(self, request, *args, **kwargs):
		self.quiz = get_object_or_404(Quiz, pk=self.kwargs['pk'])
		return super(TakeQuizView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(TakeQuizView, self).get_context_data(**kwargs)
		post_list = get_list_or_404(self.quiz.post_list.all())


		random.shuffle(post_list)
		context['quiz'] = self.quiz
		context['post_list'] = post_list
		context['label_list'] = self.quiz.label_list.all()
		return context

class CreateQuizView(LoginRequiredMixin, FormView):
	model = Quiz
	form_class = CreateQuizForm
	template_name = 'quiz/create_quiz.html'
	success_url = '/quiz/create_quiz_success'

	def form_valid(self, form):
		#task_title = form.cleaned_data['Task Title']
		#task_description = form.cleaned_data['Task Description']
		#task_upload_file = form.cleaned_data['Upload Task Posts and Labels']
		#task_num_labelers = form.cleaned_data['Min Number of Labelers']
		#task_num_posts = form.cleaned_data['Min Number of Posts']
		quiz_title = form.cleaned_data['Quiz Title']
		quiz_description = form.cleaned_data['Quiz Description']
		max_posts = form.cleaned_data['Number of Questions']
		pass_mark = form.cleaned_data['Pass Mark']
		quiz_upload_file = form.cleaned_data['Upload Quiz Posts and Labels']
		
		#participating_coders = form.cleaned_data['Participating Coders']

		quiz = form.create_quiz(quiz_title, quiz_description, max_posts, pass_mark, quiz_upload_file, self.request.user)
#		task = form.create_quiz(task_title, task_description, task_num_labelers, task_num_posts, task_upload_file, self.request.user, prerequisite)
		#form.send_email(quiz)

		return super(CreateQuizView, self).form_valid(form)

class CreateQuizSuccessView(LoginRequiredMixin, TemplateView):
	template_name = 'quiz/create_quiz_success.html'

class QuizSuccessView(LoginRequiredMixin, TemplateView):
	model = Quiz
	template_name = 'quiz/quiz_success.html'

	def dispatch(self, request, *args, **kwargs):
		self.quiz = get_object_or_404(Quiz, pk=self.kwargs['pk'])
		self.task = Task.objects.filter(prerequisite=self.quiz.pk).last()
		return super(QuizSuccessView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(QuizSuccessView, self).get_context_data(**kwargs)
		context['quiz'] = self.quiz
		context['task'] = self.task
		return context

class QuizFailView(LoginRequiredMixin, TemplateView):
	model = Quiz
	template_name = 'quiz/quiz_fail.html'

	def dispatch(self, request, *args, **kwargs):
		self.quiz = get_object_or_404(Quiz, pk=self.kwargs['pk'])
		return super(QuizFailView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(QuizFailView, self).get_context_data(**kwargs)
		context['quiz'] = self.quiz
		return context

quiz/views.py
from django.shortcuts import render
from django.shortcuts import get_list_or_404, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, TemplateView, FormView, DetailView
from .models import Quiz
from response.models import PostResponse
from post.models import Post
from task.models import Task
from label.models import Label
from nltk.metrics.agreement import AnnotationTask
from .forms import CreateQuizForm
import random
from django.db.models import Q
from django.contrib.auth import get_user_model
User = get_user_model()

class TakeQuizView(LoginRequiredMixin, TemplateView):
  model = Quiz
  template_name = 'quiz/take_quiz.html'

  def dispatch(self, request, *args, **kwargs):
    self.quiz = get_object_or_404(Quiz, pk=self.kwargs['pk'])
    return super(TakeQuizView, self).dispatch(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super(TakeQuizView, self).get_context_data(**kwargs)
    post_list = get_list_or_404(self.quiz.post_list.all())
    random.shuffle(post_list)
    context['quiz'] = self.quiz
    context['post_list'] = post_list
    context['label_list'] = self.quiz.label_list.all()
    return context

class CreateQuizView(LoginRequiredMixin, FormView):
  model = Quiz
  form_class = CreateQuizForm
  template_name = 'quiz/create_quiz.html'
  success_url = '/quiz/create_quiz_success'

  def form_valid(self, form):
    quiz_title = form.cleaned_data['Quiz Title']
    quiz_description = form.cleaned_data['Quiz Description']
    max_posts = form.cleaned_data['Number of Questions']
    pass_mark = form.cleaned_data['Pass Mark']
    quiz_upload_file = form.cleaned_data['Upload Quiz Posts and Labels']
    quiz = form.create_quiz(quiz_title, quiz_description, max_posts, pass_mark, quiz_upload_file, self.request.user)
    return super(CreateQuizView, self).form_valid(form)

class CreateQuizSuccessView(LoginRequiredMixin, TemplateView):
  template_name = 'quiz/create_quiz_success.html'

class QuizSuccessView(LoginRequiredMixin, TemplateView):
  model = Quiz
  template_name = 'quiz/quiz_success.html'

  def dispatch(self, request, *args, **kwargs):
    self.quiz = get_object_or_404(Quiz, pk=self.kwargs['pk'])
    self.task = Task.objects.filter(prerequisite=self.quiz.pk).last()
    return super(QuizSuccessView, self).dispatch(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super(QuizSuccessView, self).get_context_data(**kwargs)
    context['quiz'] = self.quiz
    context['task'] = self.task
    return context

class QuizFailView(LoginRequiredMixin, TemplateView):
  model = Quiz
  template_name = 'quiz/quiz_fail.html'

  def dispatch(self, request, *args, **kwargs):
    self.quiz = get_object_or_404(Quiz, pk=self.kwargs['pk'])
    return super(QuizFailView, self).dispatch(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super(QuizFailView, self).get_context_data(**kwargs)
    context['quiz'] = self.quiz
    return context

quiz/templates/quiz/create_quiz.html
{% extends "base_site.html" %}

{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>
&rsaquo; Create Quiz
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">

	{% crispy form  %}

</div>	
{% endblock content %}

quiz/templates/quiz/create_quiz_success.html
{% extends "base_site.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>
&rsaquo;
<a href="{% url 'admin_index' %}">Admin Home </a>
&rsaquo; Create Task Success
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">

	<div class="row">
		<div class="col-md-12">
			<h1>Hi, {{ request.user }}!</h1>
			<br>
			<p>
				You have successfully created new quiz!
			</p>			
			<br>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" style="text-align: center;">
			<input type=button value="Done" onClick="javascript:history.go(-2);">

			</a>
		</div>
	</div>
	

</div>
{% endblock content %}

quiz/templates/quiz/quiz_fail.html
{% extends "base_site.html" %}

{% block content %}
<div class="container-fluid">

	<div class="row">
		<div class="col-md-12">
			<h1>You did not pass the quiz!</h1>
			<p>
				No problem, you can retake the quiz as many time as you want! Would you like to retake the quiz?!
			</p>
			<p>Please click the button below to retake the quiz.</p>
			<br>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" style="text-align: center;">
			<a href="{% url 'quiz:take_quiz' quiz.pk %}">
				<div class="btn btn-info btn-lg start_quiz">Retake</div>
			</a>
		</div>
	</div>

</div>
{% endblock content %}

quiz/templates/quiz/quiz_success.html
{% extends "base_site.html" %}

{% block content %}
<div class="container-fluid">

	<div class="row">
		<div class="col-md-12">
			<h1>Congratulation, {{ request.user }}!</h1>
			<br>
			<p>
				You have passed the quiz! Now you are ready to work on actual task!
			</p>
			<p>Please click the button below to continue with the actual task.</p>
			<br>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" style="text-align: center;">
			<a href="{% url 'task:take_task' task.pk %}">
				<div class="btn btn-info btn-lg start_quiz">Start</div>
			</a>
		</div>
	</div>

</div>
{% endblock content %}

quiz/templates/quiz/take_quiz.html
{% extends "base_site.html" %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'quiz/css/take_quiz.css' %}">
{% endblock extrastyle %}

{% block extrascript %}
<script type="text/javascript">
	var num_posts = {{ post_list|length }};
</script>
<script type="text/javascript" src="{% static 'quiz/js/take_quiz.js' %}"></script>
{% endblock extrascript %}

{% block content %}
<div class="container-fluid">

	<div id="prolog">
		<div class="row">
			<div class="col-md-12">
				<h1>Hi there, {{ request.user }}!</h1>
				<p>
					This is a quiz to make sure that you understand how to label. You will need to complete the quiz before doing the actual task.
					Don't worry, you can take the quiz as many times as you want!
				</p>
				<p>-------------------------------------------------------</p>
				<p>Title: {{ quiz.title }}</p>
				<p>Passing Mark: {{ quiz.pass_mark }}</p>
				<p>Description: {{ quiz.description }}</p>
				<p>Number of Questions: {{ quiz.max_posts }}</p>
				<br>
				<br>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12" style="text-align: center;">
				<div class="btn btn-info btn-lg start_quiz">Start</div>
			</div>
		</div>
	</div>

	<form id="quiz_form" action="{% url 'response:create_quiz_response' quiz.pk %}" method="POST">
		{% csrf_token %} 

		{% for post in post_list %}
		<div class="row" style="display: none;">
			<div class="col-sm-12">
				<div class="loader">
					<div class="card">

						<div class="post">
							<h3>
								<span id="post_{{ post.id }}"> {{ post }}</span>
							</h3>
						</div>
						<ul>

							{% for label in label_list %}
							
							<li class="btn btn-default">
								<input id="{{ post.id }}_{{ label.id }}" type="radio" name="post_{{ post.id }}" value="{{ label.id }}">
								<label for="{{ post.id }}_{{ label.id }}" class="element-animation">{{ label }}</label>
								<div class="check"></div>
							</li>
							{% endfor %}
							
						</ul>
						
					</div>
					
				</div>
				
				<div class="text-muted">
					<span class="label"></span>
				</div>

			</div>
			<div align='center'>{{ forloop.counter }}/{{quiz.max_posts}}</div>
		</div>
		{% endfor %}
	</form>
</div>
{% endblock content %}