LabelingSystem-master/labelingsystem/labelingsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

from .views import *

admin.site.site_header = 'Social Post Analyzer'
admin.site.site_title = 'Social Post Analyzer Labeling System'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('account:login'))),
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'admin_index/$', AdminIndexView.as_view(), name='admin_index'),
    url(r'super_admin_index/$', SuperAdminIndexView.as_view(), name='super_admin_index'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^task/', include('task.urls', namespace='task')),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^response/', include('response.urls', namespace='response')),
    url(r'^classify/', include('classify.urls', namespace='classify')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url

from django.contrib.auth.views import LoginView, LogoutView
from .views import *
from .forms import *

app_name = 'account'

urlpatterns = [
    url(r'^login$', LoginView.as_view(template_name='account/login.html', redirect_field_name='home', form_class=LoginForm, redirect_authenticated_user=True), name='login'),
    url(r'^login/$', LoginView.as_view(template_name='account/login.html', redirect_field_name='home', form_class=LoginForm, redirect_authenticated_user=True), name='login'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', SignUpView.as_view(), name='signup'),
    url(r'^logout/$', LogoutView.as_view(redirect_field_name='account:login'), name='logout'),
    url(r'^account_detail/(?P<pk>[-\w]+)/$', AccountDetailView.as_view(), name='account_detail'),
    url(r'^password_change/$', AccountPasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change_success/$', AccountPasswordChangeSuccessView.as_view(), name='password_change_success'),
    url(r'^forgot_password/$', ResetPasswordRequestView.as_view(), name='forgot_password'),
    url(r'^forgot_password_success/$', ResetPasswordRequestSuccessView.as_view(), name='forgot_password_success'),
    url(r'^password_reset/$', PasswordResetConfirmView.as_view(), name='password_reset'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),name='password_reset'),
    url(r'^password_reset_success/$', AccountPasswordResetSuccessView.as_view(), name='password_reset_success'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',ActivateAccountSuccessView.as_view(), name='activate'),
    url(r'^account_activate_success/$', ActivateAccountSuccessView.as_view(), name='account_activate_success'),
    url(r'^signup_alt/$', SignUpAltView.as_view(), name='signup_alt'),
    url(r'^signup_success/$', SignUpSuccessView.as_view(), name='signup_success'),
]

classify/urls.py
from django.conf.urls import url

from .views import *

app_name = 'classify'

urlpatterns = [
  url(r'^create_classification_model/$', CreateClassificationModelView.as_view(), name='create_classification_model'),
  url(r'^create_classification_model_success/$', CreateClassificationModelSuccessView.as_view(), name='create_classification_model_success'),
  url(r'^classify_data/$', ClassifyDataView.as_view(), name='classify_data'),
  url(r'^classify_success/$', ClassifySuccessView.as_view(), name='classify_success'),
  url(r'^classify_list/$', ClassifyTaskListView.as_view(), name='classify_list'),
  url(r'^delete_classify/(?P<pk>\d+)/$', DeleteClassifyView.as_view(), name='delete_classify'),
]

labelingsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth.views import login
from .views import *

admin.site.site_header = 'CrowdTagger'
admin.site.site_title = 'CrowdTagger System'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('account:login'))),
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^admin_index/$', AdminIndexView.as_view(), name='admin_index'),
    url(r'^super_admin_index/$', SuperAdminIndexView.as_view(), name='super_admin_index'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^task/', include('task.urls', namespace='task')),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^response/', include('response.urls', namespace='response')),
    url(r'^classify/', include('classify.urls', namespace='classify')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^select2/', include('django_select2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url

from .views import *

app_name = 'post'

urlpatterns = [
  url(r'^create_post_response/(?P<task_pk>[-\w]+)&(?P<post_pk>[-\w]+)$', create_post_response, name='create_post_response'),
]

quiz/urls.py
from django.conf.urls import url

from .views import *

app_name = 'quiz'

urlpatterns = [
  url(r'^take_quiz/(?P<pk>[-\w]+)$', TakeQuizView.as_view(), name='take_quiz'),
  url(r'^quiz_success/(?P<pk>[-\w]+)$', QuizSuccessView.as_view(), name='quiz_success'),
  url(r'^create_quiz/$', CreateQuizView.as_view(), name='create_quiz'),
  url(r'^create_quiz_success/$', CreateQuizSuccessView.as_view(), name='create_quiz_success'),
  url(r'^quiz_fail/(?P<pk>[-\w]+)$', QuizFailView.as_view(), name='quiz_fail'),
]

task/urls.py
from django.conf.urls import url

from .views import *
app_name = 'task'

urlpatterns = [
  url(r'^task_list/$', TaskListView.as_view(), name='task_list'),
  url(r'^create_task/get_table/$', get_table, name = "get_table_all"),
  url(r'^create_task/get_table_all/$', get_table_all, name = "get_table"),
  url(r'^take_task/(?P<pk>[-\w]+)$', TakeTaskView.as_view(), name='take_task'),
  url(r'^task_complete/$', TaskCompleteView.as_view(), name='task_complete'),
  url(r'^task_empty/$', TaskEmptyView.as_view(), name='task_empty'),
  url(r'^create_task/$', CreateTaskView.as_view(), name='create_task'),
  url(r'^create_task_success/$', CreateTaskSuccessView.as_view(), name='create_task_success'),
  url(r'^load_database/$', LoadDatabaseView.as_view(), name='load_database'),
  url(r'^load_database_success/$', LoadDatabaseSuccessView.as_view(), name='load_database_success'),
  url(r'^load_database_fail/$', LoadDatabaseFailView.as_view(), name='load_database_fail'),
  url(r'^edit_task/$', EditTaskView.as_view(), name='edit_task'),
  url(r'^edit_task_success/$', EditTaskSuccessView.as_view(), name='edit_task_success'),
  url(r'^update_labeler/$', UpdateLabelerView.as_view(), name='update_labeler'),
  url(r'^update_labeler_success/$', UpdateLabelerSuccessView.as_view(), name='update_labeler_success'),
  url(r'^task_evaluation_list/$', TaskEvaluationListView.as_view(), name='task_evaluation_list'),
  url(r'^task_evaluation_empty/$', TaskEvaluationEmptyView.as_view(), name='task_evaluation_empty'),
  url(r'^task_evaluation_detail/(?P<pk>[-\w]+)$', TaskEvaluationDetailView.as_view(), name='task_evaluation_detail'),
  url(r'^task_participation_list/$', TaskParticipationListView.as_view(), name='task_participation_list'),
  url(r'^task_participation_empty/$', TaskParticipationEmptyView.as_view(), name='task_participation_empty'),
  url(r'^connection_list/$', ConnectionListView.as_view(), name='connection_list'),
  url(r'^connection_list/delete_connection/$', delete_connection, name='delete_connection'),
  url(r'^connection_list/(?P<pk>\d+)/$', ConnectionDetailView.as_view(), name='connection_detail'),
  url(r'^connection_list_modal/$', ConnectionListModalView.as_view(), name='connection_list_modal'),
  url(r'^connection_list_modal/delete_connection_modal/$', delete_connection_modal, name='delete_connection_modal'),
  url(r'^connection_list_modal/(?P<pk>\d+)/$', ConnectionDetailModalView.as_view(), name='connection_detail_modal'),
  url(r'^load_database_modal/$', LoadDatabaseModalView.as_view(), name='load_database_modal'),
  url(r'^merge_database/$', merge_database, name='merge_database'),
]

templates/admin_index.html
{% extends "base_site.html" %}

{% load static %}

{% block extrastyle %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock extrastyle %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>
&rsaquo; Admin Home
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">
	<div class="col-sm-6">

		<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Create New Task &nbsp <a href="{% url 'task:create_task' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to create and send new task.</p>
					</div>
				</div>				
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'task:create_task' %}" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>				
			</div>
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Edit Task &nbsp <a href="/admin/task/task/"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to edit existing task.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<!--a href="/admin/task/task/" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>	
			</div> 
		</div>
		<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Create New Quiz &nbsp <a href="{% url 'quiz:create_quiz' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to create and send new Quiz.</p>
					</div>
				</div>				
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'quiz:create_quiz' %}" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>				
			</div>
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Edit Quiz &nbsp  <a href="/admin/quiz/quiz/"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to edit existing quiz.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<!--a href="/admin/quiz/quiz/" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>	
			</div> 
		</div>
			<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Add/Remove Labeler &nbsp <a href="{% url 'task:task_participation_list'%}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Add or remove labeler to tasks.</p>
					</div>
				</div>				
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'task:task_participation_list'%}" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>				
			</div>			
		</div>
		<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Monitor Task Progress <a href="{% url 'task:task_evaluation_list' %}"><span class="glyphicon glyphicon-list-alt"></span></a></h1>
					<div class="cta-desc">
						<p>Evaluate the task you have assigned to the coders.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'task:task_evaluation_list' %}" class="btn btn-lg btn-block btn-default">View Progress</a-->
				</div>
			</div>
		</div>

        </div>
	<!--div class="col-sm-6">
                 <div class="bs-calltoaction bs-calltoaction-info">
                         <div class="row">
                                <div class="col-md-9 cta-contents">
                                        <h1 class="cta-title">Build Classifier &nbsp <a href="{% url 'task:create_task' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
                                        <div class="cta-desc">
                                                <p>Step by step interface to create and send new task.</p>
                                        </div>
                                </div>
                                <div class="col-md-3 cta-button">
                                        
                                </div>
                        </div>

                </div>

        </div-->


		{% if user.is_staff or user.is_superuser %}

		<!--div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Site Administration <span class="glyphicon glyphicon-pencil"></span></h1>

					<div class="cta-desc">
						<p>Go directly to the django admin site where you can view and make changes to the database.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<a href="{% url 'admin:index' %}" class="btn btn-lg btn-block btn-default">Inspect</a>
				</div>
			</div>
		</div-->
			
		{% endif %}

	</div>
</div>
{% endblock content %}

templates/base_site.html
{% extends "base.html" %}

{% load i18n static %}

{% block body %}
<body>

<!-- Container -->
<div id="container">

    <!-- Navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-header">
            <!--a class="navbar-left" href="{% url 'home' %}"><img class="navbar-logo" src="{% static 'img/ucipt_logo.png' %}"></a-->
            <a class="navbar-brand" href="{% url 'home' %}">  CrowdTagger              </a>
         

        </div>
        <div class="container-fluid">
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="navbar-form navbar-right">
                    <a href="/account/account_detail/1/"> Hello, {{ user }}               </a>		  
                    <!--a href="/account/account_detail/1/"> About us               </a-->             
 
		    <!--a href="/account/password_change"><small>Reset</small></a-->
                    <a href="{% url 'account:logout' %}"><label class="btn btn-info">Logout</label></a>
                    <a href="{% url 'about' %}"><label class="btn btn-info">About us</label></a>
		   <!--select id="addlab">
			  <option value="Admin">Admin</label></option>
			  <option value="Labeler">Labeler</option>
		   </select-->			   			
		
		    {% if  user.is_staff and request.build_absolute_uri != "http://dblab-rack30.cs.ucr.edu/task/task_list/" and request.build_absolute_uri != "http://dblab-rack30.cs.ucr.edu/task/task_empty/" %} 			  
                    	<a href="{% url 'task:task_list' %}"><label class="btn btn-info">Labeler View</label></a>
				
		    {% elif user.is_staff  %}
                        <a href="{% url 'home' %}"><label class="btn btn-info">Admin View</label></a>			
		   {% endif %}		
		   	
                </ul>
            </div>
        </div>
    </nav>

    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'home' %}">{% trans 'Home' %}</a>
    </div>
    {% endblock %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% endblock %}
        {% block content %}{% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->
</body>
{% endblock body %}

templates/index.html
{% extends "base_site.html" %}

{% load static %}

{% block extrastyle %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock extrastyle %}

{% block content %}
<meta http-equiv="refresh" content="0; url=http://dblab-rack30.cs.ucr.edu/task/task_list" />
<div class="container-fluid">
	<div class="col-sm-12">
		{% if not user.is_staff and not user.is_superuser %}
		<!--div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Profile &nbsp <span class="glyphicon glyphicon-user"></span></h1>
					<div class="cta-desc">
						<p>View your profile and check your progress.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<a href="{% url 'account:account_detail' user.pk %}" class="btn btn-lg btn-block btn-default">View Profile</a>
				</div>
			</div>
		</div-->

		
		<!--div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">My Tasks &nbsp <span class="glyphicon glyphicon-list-alt"></span></h1>
					<div class="cta-desc">
						<p>View the list of tasks given to you.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<a href="{% url 'task:task_list' %}" class="btn btn-lg btn-block btn-default">Get it done!</a>
				</div>
			</div>
		</div-->
		{% endif %}

		{% if user.is_staff %}
		<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Admin Index &nbsp <span class="glyphicon glyphicon-cog"></span></h1>
					<div class="cta-desc">
						<p>Create and send new tasks. Evaluate existing task.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<a href="{% url 'admin_index' %}" class="btn btn-lg btn-block btn-default">Inspect</a>
				</div>
			</div>
		</div>
			
		{% endif %}
		{% if user.is_superuser %}
                <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="row">
                                <div class="col-md-9 cta-contents">
                                        <h1 class="cta-title">Admin Index &nbsp <span class="glyphicon glyphicon-cog"></span></h1>
                                        <div class="cta-desc">
                                                <p>Create and send new tasks. Evaluate existing task.</p>
                                        </div>
                                </div>
                                <div class="col-md-3 cta-button">
                                        <a href="{% url 'super_admin_index' %}" class="btn btn-lg btn-block btn-default">Inspect</a>
                                </div>
                        </div>
                </div>

                {% endif %}

	</div>
</div>
{% endblock content %}

templates/super_admin_index.html
{% extends "base_site.html" %}

{% load static %}

{% block extrastyle %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock extrastyle %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'home' %}">Home </a>
&rsaquo; SuperAdmin Home
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">
	<div class="col-sm-6">

		<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Create New Task &nbsp <a href="{% url 'task:create_task' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to create and send new task.</p>
					</div>
				</div>				
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'task:create_task' %}" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>				
			</div>
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Edit Task &nbsp <a href="/admin/task/task/"<span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to edit existing task.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<!--a href="/admin/task/task/" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>	
			</div> 
		</div>
		<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Create New Quiz &nbsp <a href="{% url 'quiz:create_quiz' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to create and send new Quiz.</p>
					</div>
				</div>				
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'quiz:create_quiz' %}" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>				
			</div>
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Edit Quiz &nbsp  <a href="/admin/quiz/quiz/"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Step by step interface to edit existing quiz.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<!--a href="/admin/quiz/quiz/" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>	
			</div> 
		</div>
			<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Add/Remove Labeler &nbsp <a href="{% url 'task:task_participation_list'%}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
					<div class="cta-desc">
						<p>Add or remove labeler to tasks.</p>
					</div>
				</div>				
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'task:task_participation_list'%}" class="btn btn-lg btn-block btn-default">Start</a-->
				</div>				
			</div>			
		</div>
		<div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Monitor Task Progress <a href="{% url 'task:task_evaluation_list' %}"><span class="glyphicon glyphicon-list-alt"></span></a></h1>
					<div class="cta-desc">
						<p>Evaluate the task you have assigned to the labelers.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<!--a href="{% url 'task:task_evaluation_list' %}" class="btn btn-lg btn-block btn-default">View Progress</a-->
				</div>
			</div>
		</div>
		<div class="bs-calltoaction bs-calltoaction-info">
                        <div class="row">
                                <div class="col-md-9 cta-contents">
                                        <h1 class="cta-title">Administration View <a href="/admin/"><span class="glyphicon glyphicon-list-alt"></span></a></h1>
                                        <div class="cta-desc">
                                                <p>View database</p>
                                        </div>
                                </div>
                                <div class="col-md-3 cta-button">
                                        <!--a href="/admin/" class="btn btn-lg btn-block btn-default">View</a-->
                                </div>
                        </div>
                </div>


		{% if user.is_staff or user.is_superuser %}

		<!--div class="bs-calltoaction bs-calltoaction-info">
			<div class="row">
				<div class="col-md-9 cta-contents">
					<h1 class="cta-title">Site Administration <span class="glyphicon glyphicon-pencil"></span></h1>

					<div class="cta-desc">
						<p>Go directly to the django admin site where you can view and make changes to the database.</p>
					</div>
				</div>
				<div class="col-md-3 cta-button">
					<a href="{% url 'admin:index' %}" class="btn btn-lg btn-block btn-default">Inspect</a>
				</div>
			</div>
		</div-->
			
		{% endif %}

	</div>
	

	<div class="col-sm-6">
		 <div class="bs-calltoaction bs-calltoaction-info">
                         <div class="row">
                                <div class="col-md-9 cta-contents">
                                        <h1 class="cta-title">Build Classifier &nbsp <a href="{% url 'classify:create_classification_model' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
                                        <div class="cta-desc">
                                                <p>Step by step interface to build a classifier.</p>
                                        </div>
                                </div>
                                <div class="col-md-3 cta-button">
                                        <!--a href="{% url 'classify:create_classification_model' %}" class="btn btn-lg btn-block btn-default">Start</a-->
                                </div>
                        </div>
                              <div class="row">
                                <div class="col-md-9 cta-contents">
                                  <h1 class="cta-title">Edit Classifier &nbsp <a href="/admin/classify/classify/"<span class="glyphicon glyphicon-pencil"></span></a></h1>
                                  <div class="cta-desc">
                                    <p>Step by step interface to edit existing classifier.</p>
                                  </div>
                                </div>
                                <div class="col-md-3 cta-button">
                                  <!--a href="/admin/task/task/" class="btn btn-lg btn-block btn-default">Start</a-->
                                </div>  
                              </div> 
		</div>

	</div>
	<div class="col-sm-6">
                 <div class="bs-calltoaction bs-calltoaction-info">
                  <div class="row">
                                <div class="col-md-9 cta-contents">
                                        <h1 class="cta-title">View Classifier Task &nbsp <a href="{% url 'classify:classify_list' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
                                        <div class="cta-desc">
                                                <p>View your scheduled training task here.</p>
                                        </div>
                                </div>
                                <div class="col-md-3 cta-button">
                                        <!--a href="{% url 'task:create_task' %}" class="btn btn-lg btn-block btn-default">Start</a-->
                                </div>
                        </div>
                         <div class="row">
                                <div class="col-md-9 cta-contents">
                                        <h1 class="cta-title">Classify data &nbsp <a href="{% url 'classify:classify_data' %}"><span class="glyphicon glyphicon-pencil"></span></a></h1>
                                        <div class="cta-desc">
                                                <p>Step by step interface to classify data.</p>
                                        </div>
                                </div>
                                <div class="col-md-3 cta-button">
                                        <!--a href="{% url 'task:create_task' %}" class="btn btn-lg btn-block btn-default">Start</a-->
                                </div>
                        </div>

                </div>

        </div>

</div>

</div>
{% endblock content %}